# Generated by Django 4.2.14 on 2024-07-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookworm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='edited_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='post',
            name='exerpt',
            field=models.TextField(blank=True),
        ),
    ]
