# Generated by Django 4.2.14 on 2024-08-10 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookworm', '0006_genre_book_cover_photo_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterField(
            model_name='comment',
            name='comments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookworm.book'),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
