# Generated by Django 4.2.14 on 2024-08-11 13:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookworm', '0007_alter_book_options_alter_comment_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_photo',
            field=cloudinary.models.CloudinaryField(default="{% url 'static/images/logo.png' %}", max_length=255, verbose_name='image'),
        ),
    ]
