# Generated by Django 4.2.14 on 2024-08-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_profile_username'),
        ('bookworm', '0008_alter_book_cover_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='likes',
            field=models.ManyToManyField(related_name='book_likes', to='profiles.profile'),
        ),
    ]
