# Generated by Django 4.2.14 on 2024-08-13 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookworm', '0009_book_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='sub_genre',
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookworm.genre'),
        ),
    ]
